version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/var/code
    depends_on:
      - app

  app:
    build: ./php
    volumes:
      - ./code:/var/code
